//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ordermgt.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class category
    {
        public int cat_id { get; set; }

        [Display(Name = "Order")]
        [Required(ErrorMessage = "*")]
        public string cat_name { get; set; }

        [Display(Name = "Delivery Status")]
        [Required(ErrorMessage = "*")]
        public byte cat_status { get; set; }

        [Display(Name = "Product")]
        [Required(ErrorMessage = "*")]
        public string cat_product { get; set; }


        [Display(Name = "Date")]
        [Required(ErrorMessage = "*")]
        [DisplayFormat(DataFormatString = "(00:d)")]// data format 
        public Nullable<System.DateTime> cat_date { get; set; }

        public Nullable<int> cat_driver { get; set; }
    
        public virtual user user { get; set; }
    }
}
