//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ordermgt.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class category
    {
        [Key]

        public int cat_id { get; set; }

        [Display(Name = "Category Name")]
        [Required(ErrorMessage = "*")]
        public string cat_name { get; set; }

        [Display(Name = "Status")]
        [Required(ErrorMessage = "*")]
        public byte cat_status { get; set; }
    }
}
